spring:
 profiles:
  active:
  - dev
---
spring:
 profiles: dev
 application:
  name: microservice-config-atguigu-dev
---
sping:
 profiles: test
 application:
  name: microservice-config-atguigu-test
